const teams = [
    { name: "Anaheim Ducks", abbrev: "ANA", id: 24 },
    { name: "Arizona Coyotes", abbrev: "ARI", id: 53 },
    { name: "Boston Bruins", abbrev: "BOS", id: 6 },
    { name: "Buffalo Sabres", abbrev: "BUF", id: 7 },
    { name: "Calgary Flames", abbrev: "CGY", id: 20 },
    { name: "Carolina Hurricanes", abbrev: "CAR", id: 12 },
    { name: "Chicago Blackhawks", abbrev: "CHI", id: 16 },
    { name: "Colorado Avalanche", abbrev: "COL", id: 21 },
    { name: "Columbus Blue Jackets", abbrev: "CBJ", id: 29 },
    { name: "Dallas Stars", abbrev: "DAL", id:25 },
    { name: "Detroit Red Wings", abbrev: "DET", id: 17 },
    { name: "Edmonton Oilers", abbrev: "EDM", id: 22 },
    { name: "Florida Panthers", abbrev: "FLA", id: 13 },
    { name: "Los Angeles Kings", abbrev: "LAK", id: 26 },
    { name: "Minnesota Wild", abbrev: "MIN", id: 30 },
    { name: "Montreal Canadiens", abbrev: "MTL", id:8 },
    { name: "Nashville Predators", abbrev: "NSH", id: 18, },
    { name: "New Jersey Devils", abbrev: "NJD", id: 1 },
    { name: "New York Islanders", abbrev: "NYI", id: 2 },
    { name: "New York Rangers", abbrev: "NYR", id: 3 },
    { name: "Ottawa Senators", abbrev: "OTT", id: 9 },
    { name: "Philadelphia Flyers", abbrev: "PHI", id: 4 },
    { name: "Pittsburgh Penguins", abbrev: "PIT", id: 5 },
    { name: "San Jose Sharks", abbrev: "SJS", id: 28 },
    { name: "Seattle Kraken", abbrev: "SEA", id: 55 },
    { name: "St. Louis Blues", abbrev: "STL", id: 19 }, 
    { name: "Tampa Bay Lightning", abbrev: "TBL", id: 14 },
    { name: "Toronto Maple Leafs", abbrev: "TOR", id: 10 },
    { name: "Vancouver Canucks", abbrev: "VAN", id: 23 },
    { name: "Vegas Golden Knights", abbrev: "VGK", id: 54 },
    { name: "Washington Capitals", abbrev: "WSH", id: 15 },
    { name: "Winnipeg Jets", abbrev: "WPG", id: 52 },
];

export default teams;